### ISSUE TITLE
Separation of localisation keys into separate metadata

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#154]
Related #26 #12 #24 #3 #43

---

### Tasks (current; assigned to @tukusejssirs) <a name="tasks_ts"></a>

- [x] fill `original key name` column:
   - where there are multiple keys, they are comma-space-separated;
   - `abachum`, `anastasius`, `audifax`, `emerentiana`, `hyginus`, `marcellusI`, `marius`, `martina`, `paulTheFirstHermit`, `peterNolasco`, `prisca`, `teophorus` are currently not in romcal, as they was celebrated in `general` before 1969; it was added as a minor work on the Extra-Ordinary Form calendar;
- [x] lowercase all non-proper words:
   - [x] saint/blessed;
   - [x] titles;
- [x] change number `1000` to `many`;
- [ ] merge `firstName` and `additionalFirstName` columns and `surname` and `additionalSurname` and separate the values by comma-space (`, `);
- [ ] separate `notes` column into:
   - [ ] `alternativeName` and `alternativeSurname`;
   - [x] `name distinguisher` used to add an additional part to the key name to differentiate the keys from each other;
   - [ ] `originalName` and `originalSurname` (name/surname in original language and form; this might be an array or string; this should be protected and nobody should be able to override the value unless done in the sanctoral);
   - [ ] `collectiveName` (usual name for the particular person(s); like `Vietnamese Martyrs`; this might be unnecessary);
- [x] change the dates format to `Jan 1` (or `Jan 1, 2020`);
- [x] corrected some data (like `Alponsus` instead of `Alphonsus`);
- [x] merge `events` sheet into `persons`;
- [x] rename `persons` sheet to `sanctoral`;
- [x] remove unnecessary columns:
   - [x] `not celebrated in`;
   - [x] `celebrated in`;
   - [x] `celebration date (general calendar)`;
   - [x] `general or national calendar?`;
   - [x] `celebration date (cal1962 or EOC)`;
   - [x] `celebration date (cal1969 or GRC)`;
- [x] fill the `name distinguisher` when required;

### Tasks for all locales

These tasks should be done separately for each and every locale.

- [ ] separate the localisation keys of a particular locale into separate metadata;
- [ ] save the metadata values into DB or `.po` files (or whatever else according to the chosen localisation tool);

### Tasks done only once

These tasks are to be done only once and are (mostly) connected with the processing of the localisation data.

- [ ] create auxiliary functions that would process the localisation data;
- [ ] document everything (dev and user docs in Wiki);

---

### Description

I have already create some partial separation in Google Sheets [here](https://drive.google.com/drive/folders/1hGvsFkYn_cBH9cWO9quYjr0kXi6y8fK-?usp=sharing) (there multiple folders base on the particular field, which partially overlap). Particularly used for this issue is [l10n/romcal_l10n_enUs](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit?usp=sharing), which contains my work on this issue for `en.js`. This should be done for all supported languages.

After the separation process is done and the extracted data is placed into a DB (or whatever we choose), we should create some functions to work with the data. Below are functions that would be used in localisation (localisation tool and localisation process) that came to my mind, but I am positive that I have not listed all necessary functions yet.

We might need to create a separate repositories: one for the localisation tool and one for the localisation files (which would contain the actual strings).

As for now, there is nothing written in stone, therefore you may (or should) suggest some improvements.

---

After the the separation of the separate metadata (and after the metadata localisation), we need to define the celebrations (maybe only person celebrations) by collecting the metadata of the celebration; see below the example. Note that the key form (`vianneyJohnMary`) might be changed to `nameSurname` (i.e. `johnMaryVianney`). Also, I have not listed all the different metadata types.

You could also read my [original description](https://github.com/romcal/romcal/issues/12#issuecomment-391059017) of this.

```js
vianneyJohnMary{
  .surname="Vianney",  // It might be a [nobiliary particle](https://en.wikipedia.org/wiki/Nobiliary_particle), too
  .name="John Mary",   // All first names
  .holiness="Saint",   // This might be an int; todo: find better name instead of 'holiness'; options: st/sts/bl/bls
  .title="priest",     // Comma-separated list
  .number=1,           // How many persons?; only used in person celebrations only
  .sex="male"          // male/female/mix; only used in person celebrations only
}
```

---

The separation of the keys into separate metadata would result also in the needs of a list of all titles of persons. From the localisation perspective, we need not only a mere list, but (because of only languages) also the following forms of each and every title:
- singular masculine form in nominative case;
- singular masculine form in genitive case;
- plural masculine form in nominative case;
- plural masculine form in genitive case;
- singular feminine form in nominative case;
- singular feminine form in genitive case;
- plural feminine form in nominative case;
- plural feminine form in genitive case;

In English (and maybe other languages), the nominative and genitive form in particular gender and number would be same. In Slovak (or Czech, German, etc) it won’t be the same.

Example:

```js
// Note that genitive forms might be omitted in English, as they should always default
//   to the nominative case, but it must not be omitted (for other languages)
//   when the genitive form is different from the nominative form
abbot{
  .sgmn="abbot",     // SinGular Masculine form in Nominative
  .sgmg="abbot",     // SinGular Masculine formin Genitive
  .plmn="abbots",    // PLural Masculine form in Nominative
  .plmg="abbots",    // PLural Masculine form in Genitive
  .sgfn="abbess",    // SinGular Feminine form in Nominative
  .sgfg="abbess",    // SinGular Feminine form in Genitive
  .plfn="abbesses",  // PLural Feminine form in Nominative
  .plfg="abbesses"   // PLural Feminine form in Genitive
}
```

---

### `capitalizeFirstLetter`

The localised strings should be written in lowercase, i.e. no capitalisation rules should be applied unless it must be written in a special way (e.g. `saint` should be written in lowercase, but `Peter` should have upppercase first letter).

This function should be used when a general noun (like `preface`) is part of the proper name (like the `Preface of the Apostles`).

This function might need to be remained to `titlecase` (or similar) if you wish.

Besides the string (key), it must be supplied with an optional argument that would tell the function if the function should:

a. capitalise the first letter of the first word only:
   - Some languages (e.g. Slovak or Hungarian) capitalise only the first letter of the first word in titles.

b. capitalise the first letters of all words:
   - I presume this is the American style of writing the titles.
   
c. capitalise the first letter on of words that are more than four letters long (aka [_titlecase_](https://saijogeorge.com/title-case-converter/) capitalisation):
   - I presume this is the traditional/British style of writing the titles.

### `titlesUsingThe` (in English only)

`evangelist` and `apostle` are titles, therefore there is no the like in St James the Apostle, rather St James, Apostle.

However, sometimes these celebrations are output using the `the` (i.e. `St James the Apostle`), therefore there should be a function that would do this, but only for `evangelist` and `apostle` titles.

This function might not be a function from the user perspective, but rather a general romcal option that the user should be able to set to a Boolean value.

Also, we need to decide which format should be the default one. I suggest to use the one that the official calendar (printed/published) for the particular country uses, but only if that calendar is officially published in English. If it is not published in English, we still should have a default value set in `general` calendar.

---

As the localisation strings after the separation of localisation keys will be a subset of the current (`v1.3.x`) localisation strings, I suggest the following rules:
- key names for person localisation strings should be generated from `en` name prefix, names and surnames and a special ‘unique-maker’ fields (if needed) only and only if the particular field is not empty. There might be some person keys that would contain person names only. All non-Latin characters should be substituted (diacritics removed) and non-alfanumeric (`[^A-Za-z0-9]`) chars are omited. Also all spaces are removed and the letter that followed a space is capitalised (to form lowerCamelCase). For example: St Adalbert of Prague → `adalbertOfPrague`.

These keys will create some complications when defining joint celebrations in calendars. In joint celebration definitions in calendars, we should require to define a unique celebration ID/key. This might be also generated, but still users need to know the ID/key, e.g. when the calendarist need to drop that event in a particular (national) calendar.

**Comment by tukusejssirs** [comment]
@emagnier, could you find some time to comment on this issue please? I know we talked about this already, but I’d like to hear direct input from you on how _exactly_ we’d like to accomplish this, as I cannot do it by myself (_you_ are the programmer, not me :smiley:).

I know that this issue depends on #43, that is we must first choose a concreate tool and then adapt the separation process to it.

Also, we might need to revise what (categories) to translate. I wish we would translate everything from the end-user perspective and wisely choose what should be customisable. As we already talked in #158, the `locale` should not be defined in the _calendar_ configuration, therefore there might be a need to create a separate config per _locale_, where there would be the default _locale-specific_ settings. The `locale` key/option itself should not be defined within romcal codebase—it should be configured by the end-user only. Same would apply for the _particular calendars_, while the GRC would be the default (i.e. when no `calendar` as general romcal option would be supplied by the end-user).

**Comment by emagnier** [comment]
@tukusejssirs thank you for all this great work of preparation! I will recognise that I didn't had time yet to dive into this topic, and especially everything related to i18n. But I just want to tell you that this is something on my list of things I would like to tackle soon!

**Comment by tukusejssirs** [comment]
@emagnier, I just want to note that it is not yet finished. And I really don’t want to continue with the process until I hear from you and @pejulian, how exactly we want to accomplish this, as I won’t create the underlying code.

Sidenote: I know that first the build process must be improved/simplified/reworked, only then we can work on this (and other) big features. :smiley:

**Comment by tukusejssirs** [comment]
@emagnier, should I also merge the titles into one column? Again: the titles would be comma-space-separated.

**Comment by emagnier** [comment]
In fact actually my script already merge the 3 columns of titles into an Array of title. So I would say it's not necessary.

In YAML, array are written like that:
```yaml
title:
  - title 1
  - title 2
  - title 3
```

And actually I'm wondering if for the names should be written them the same way:
```yaml
name:
  - name 1
  - name 2

# or one-liner:

name: name 1, name 2
```

I personally do prefer the array style for titles, but might prefer the one-liner for the name (comma separated). What do you think?

However in your Google document, it change nothing (you can keep the name comma separated).

**Comment by emagnier** [comment]
And about the titles, I'm also wondering if we should have a kind of group of titles.

Because for example, `Martyr` and `the First Martyr` are in reality the same, they are both `Martyr`, but because they are 2 different string, they will be treated differently.

Or should we have somewhere else a list of allowed titles, that could be grouped here. So if I'm requesting all celebrations for martyrs, I will get as well Stephen the First Martyr. In fact we already have that in romcal, in `/src/constants/Titles.js`, but it's quite limited.

**Comment by tukusejssirs** [comment]
> I personally do prefer the array style for titles, but might prefer the one-liner for the name (comma separated). What do you think?

Well, I have no preference. I see why you like one-liner arrays for names and surnames, and multi-liner ones for titles (reason: readability). Therefore we could format it that way.

> And about the titles, I'm also wondering if we should have a kind of group of titles.

From l10n point of view, we definitely should have a list of titles (see the [`titles](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit#gid=24811360) sheet, where I have listed all titles we currently use in romcal).

Indeed `martyr` and `the first martyr` are same titles. I suggest that even St Stephen the First Martyr should be defined with `martyr` title and romcal should automatically create the celebration name using `the` (same would happen if the user chooses the `the Apostle` format instead of `, Apostle`).

> Or should we have somewhere else a list of allowed titles, that could be grouped here. So if I'm requesting all celebrations for martyrs, I will get as well Stephen the First Martyr. In fact we already have that in romcal, in `/src/constants/Titles.js`, but it's quite limited.

This reminded me that the title order (titles of a particular person) is somewhat set. I mean that we never have `martyr and pope`, but `pope and martyr`. We could programmaticaly enforce the order, even if the title order in the definition is not correct. The order somewhat sorts the persons too (pope is listed before priest). Here’s a partial order (might be incorrect):

1. pope > bishop > priest deacon;
2. abbot > virgin > monk > religious;
3. martyr
4. patron of something

**Comment by emagnier** [comment]
Yes we could take care of the order programmatically.
About St Stephen the First Martyr, I think you forgot the `First` in your exemple: the First Martyr. So only add `the` will not work.

For this reason I suggest to have some variants defined, and grouped under one main title.
```yaml
# Titles

Patron of Europe:
  - variant A for the title of Patron of Europe
  - variant B for the title of Patron of Europe

Martyr:
  - the First Martyr
  - variant B for the title of Martyr
  - variant C for the title of Martyr
```

What do you think?

**Comment by tukusejssirs** [comment]
> About St Stephen the First Martyr, I think you forgot the `First` in your exemple: the First Martyr. So only add `the` will not work.

Yes, I forget it to _write_ about it. On the other hand, as there is only _one_ first martyr, this could be fixed via one `if` statement.

> For this reason I suggest to have some variants defined, and grouped under one main title.

I think we definately should have a _place_ (or two) where we would list all the possible titles.

#### From localisation point of view

In the database/file, we would have all the possible titles translated into all supported languages. See [this sheet](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit#gid=24811360) to see what I mean.

#### From calendar/romcal point of view

It is up to you (and @pejulian) how will it work. As for the patron of a place, I suggest that we should define that in the calendar as an additional property (or how you call it), for example something like `patronOf: "Europe` would generate additional title `Patron of Europe`.

As for the _title variants_, I am not exactly sure what you mean. _Martyr_ title is alway _martyr_, _pope_ always _pope_.

However, if by variants you mean something like _the first martyr_ vs _protomartyr_ (which are absolute synonyms), which I wish to be implemented, then I have no idea of the best kind of implementation. There might be variantion in the casing (e.g. `Patron of Europe` vs `patron of Europe`, i.e. the celebration name is not in titlecase, but sentence case) or (in some languages other than English) output of celebration in nominative or genitive grammer case.

**Comment by emagnier** [comment]
> On the other hand, as there is only one first martyr, this could be fixed via one if statement.

As much as possible, I would avoid the "if" statement for the contents in the codebase. This is why I recently moved the default calendar settings to calendar files. Here, even if we only have one case at the moment (but I think no), it might be worth making things a little more generic. This will allow to deal with similar cases in the future, while keeping the codebase simple and clean. All the patron titles might be also concerned by these feature.

> It is up to you (and @ pejulian) how will it work. As for the patron of a place, I suggest that we should define that in the calendar as an additional property (or how you call it), for example something like patronOf: "Europe would generate additional title Patron of Europe.

Like I just wrote above, I prefer to keep things simple here. So I will recommend to have a main title `Patron` that will also contain all its possible variants. 

Here an example of what could looks like the file that define all possible titles:

```yaml
Abbot:
Apostle:
Archangel:
Bishop:
  - Archbishop of Canterbury
Deacon:
Doctor:
Evangelist:
Hermit:
    - the First Hermit
Martyr:
    - the First Martyr
Missionary:
Monk:
Patron:
    - Patron of Europe
    - Patron of Quebec
    - Patron of Russia
    - Patron of Spain
    - Principal Patron of Canada
    - Secondary Patron of France
Pope:
Priest:
Prophet:
Religious:
Virgin:
Confessor:
the Eternal High Priest:
Husband of Mary:
```

Then a saint could have for example the title of `Martyr`, or more specifically the title of `the First Martyr`.

And from there, we will be able to look up all saints that are `Martyr` (it will include `the First Martyr`), same for `Patron` (it will include all Patron variants). Or target specifically an exact match of a title name (like `the First Hermit`).

> In the database/file, we would have all the possible titles translated into all supported languages. See this sheet to see what I mean.

I think this is the job of a i18n tool. The only things we will have to define will be the patterns to build a title correctly in the concerned language.

**Comment by tukusejssirs** [comment]
#### Original keys

On the original key: All keys from `en.js` have been paired with the new key (for separated persons). The old keys are listed in the `original key` column. If a person has multiple old keys, they are comma-space-separated, e.g. `adalbertOfPrague` has the following old keys: `saintGeorgeMartyrSaintAdalbertBishopAndMartyr, saintAdalbertBishopAndMartyr, saintAdalbertBishopAndMartyrSaintFidelisOfSigmaringenPriestAndMartyr`

#### Duplicate keys

While I was matching old keys to the new ones, I have found the following duplicates:
- `saintsCosmasAndDamian`, `saintsCosmasAndDamianMartyrs`;
- `saintHedwigReligiousOrSaintMargaretMaryAlacoqueVirgin`, `saintHedwigReligiousSaintMargaretMaryAlacoqueVirgin`;
- `saintJohnOfGodPriest`, `saintJohnOfGodReligious`;
- `saintJuanDiego`, `saintJuanDiegoCuauhtlatoatzin`;
- `saintMarkApostle`, `saintMarkTheEvangelist`;
- `saintOliverPlunketBishopAndMartyr`, `saintOliverPlunkettBishopAndMartyr`;
- `saintPioOfPietralcina`, `saintPioOfPietrelcinaPadrePioPriest`;
- `saintEzekielMorenoBishop`, `saintEzequielMorenoBishop`;
- `saintsLawrenceRuizAndCompanionsMartyrs`, `saintLorenzoRuizAndCompanionsMartyrs`.

There still might be some other duplicates, but it is very hard to see which keys (persons) are same and which just have similar/same names.

#### Church dedication

The name of the dedication of a church to some saint(s) should be generated from the keys of the saints.

#### Naming issues

Some names of the persons may/must be changed, either because they must be anglicised (e.g. `Maria` → `Mary`) or there are multiple ways their name is written and we need to choose which one we will use.

#### Missing celebrations

Missing celebrations:
- [May 29] St Paul IV, Pope [optional memorial] → `general.js`

#### Other remarks

I have left some the `patronOf` titles in the title column(s), mostly because those celebrations are celebrated only in one particular country. Still I think they should be moved out from the _regular_ titles assigned to persons in the sanctoral and that they should be added in the celebration definitions for the particular calendar.

Most of the self-assigned tasks in [here](https://github.com/romcal/romcal/issues/154#tasks_ts) I have already fulfilled. On those tasks I have not done yet:
- merge `firstName` and `additionalFirstName` columns and `surname` and `additionalSurname`:
   - I think that after all, I won’t do this for you can quite easily join those columns. If you would rather want me to do this, just say so.
- separate `notes` column into multiple columns:
   - This has been partially done. I have already checked the `notes` column values and moved them to one of the following columns (those values that are just mere notes, where kept in `notes`):
      - `name distinguisher`;
		- `collective name`;
		- `birth name`;
		- `native name`;
		- `alternative name`.

   - Most values in these columns are not yet filled in.
   - Every key that was non-unique, recieved a value in the `name distinguisher` column, and thus it was made unique.

If you would like to make any changes, you are most welcome to them directly in the sheet (a sidenote: I have given edit permissions to @emagnier).

---

TODO: @tukusejssirs
- Localise some new keys (introduced by commit containing Chinese calendar) from `en` to `sk`.

**Comment by emagnier** [comment]
> I have left some the patronOf titles in the title column(s), mostly because those celebrations are celebrated only in one particular country. Still I think they should be moved out from the regular titles assigned to persons in the sanctoral and that they should be added in the celebration definitions for the particular calendar.

I agree, this could be solve with an `appendTitle` property in the calendars, to add all the "Patron of..." for a particular region. We may have a lot more of them when we will introduce diocesan calendars.

> merge firstName and additionalFirstName columns and surname and additionalSurname

Right, it can be done automatically when importing data.

**Comment by tukusejssirs** [comment]
> > On the other hand, as there is only one first martyr, this could be fixed via one if statement.
> 
> As much as possible, I would avoid the "if" statement for the contents in the codebase. This is why I recently moved the default calendar settings to calendar files. Here, even if we only have one case at the moment (but I think no), it might be worth making things a little more generic. This will allow to deal with similar cases in the future, while keeping the codebase simple and clean. All the patron titles might be also concerned by these feature.
> 
> > It is up to you (and @ pejulian) how will it work. As for the patron of a place, I suggest that we should define that in the calendar as an additional property (or how you call it), for example something like patronOf: "Europe would generate additional title Patron of Europe.
> 
> Like I just wrote above, I prefer to keep things simple here. So I will recommend to have a main title `Patron` that will also contain all its possible variants.
> 
> Here an example of what could looks like the file that define all possible titles:
> 
> ```yaml
> Abbot:
> Apostle:
> Archangel:
> Bishop:
>   - Archbishop of Canterbury
> Deacon:
> Doctor:
> Evangelist:
> Hermit:
>     - the First Hermit
> Martyr:
>     - the First Martyr
> Missionary:
> Monk:
> Patron:
>     - Patron of Europe
>     - Patron of Quebec
>     - Patron of Russia
>     - Patron of Spain
>     - Principal Patron of Canada
>     - Secondary Patron of France
> Pope:
> Priest:
> Prophet:
> Religious:
> Virgin:
> Confessor:
> the Eternal High Priest:
> Husband of Mary:
> ```
> 
> Then a saint could have for example the title of `Martyr`, or more specifically the title of `the First Martyr`.
> 
> And from there, we will be able to look up all saints that are `Martyr` (it will include `the First Martyr`), same for `Patron` (it will include all Patron variants). Or target specifically an exact match of a title name (like `the First Hermit`).
> 
> > In the database/file, we would have all the possible titles translated into all supported languages. See this sheet to see what I mean.
> 
> I think this is the job of a i18n tool. The only things we will have to define will be the patterns to build a title correctly in the concerned language.

**Comment by tukusejssirs** [comment]
> > On the other hand, as there is only one first martyr, this could be fixed via one if statement.
> 
> As much as possible, I would avoid the "if" statement for the contents in the codebase. This is why I recently moved the default calendar settings to calendar files. Here, even if we only have one case at the moment (but I think no), it might be worth making things a little more generic. This will allow to deal with similar cases in the future, while keeping the codebase simple and clean. All the patron titles might be also concerned by these feature.
>
> […]
>
> > I have left some the `patronOf` titles in the title column(s), mostly because those celebrations are celebrated only in one particular country. Still I think they should be moved out from the regular titles assigned to persons in the sanctoral and that they should be added in the celebration definitions for the particular calendar.
> 
> I agree, this could be solve with an `appendTitle` property in the calendars, to add all the "Patron of..." for a particular region. We may have a lot more of them when we will introduce diocesan calendars.

Okay, do as you wish. There should be `the protomartyr` alternative to `the first martyr` though.

I just want to note that besides `appendTitle` (or rather `addTitle`), we might also need `removeTitle`. Some of the person celebrations have different titles in different particular calendars (I wish all of them would use same titles for a particular person with the exception of the `patron` titles, but that might never happen).

> > It is up to you (and @ pejulian) how will it work. As for the patron of a place, I suggest that we should define that in the calendar as an additional property (or how you call it), for example something like patronOf: "Europe would generate additional title Patron of Europe.
> 
> Like I just wrote above, I prefer to keep things simple here. So I will recommend to have a main title `Patron` that will also contain all its possible variants.

Okay.

> Here an example of what could looks like the file that define all possible titles: […]
>
> Then a saint could have for example the title of `Martyr`, or more specifically the title of `the First Martyr`.

Looks good to me.

Just a note: I am not sure if the `husband of Mary` should be considered a title (although I have listed them as titles and/or surnames). I think it could be considered as an _attribute_. Such attributes might be even those that are of Our Lady, like `Help of Christians`, `Mediatrix` (etc) or of Jesus like `the Eternal High Priest` or `the King`. What do you think?

> > In the database/file, we would have all the possible titles translated into all supported languages. See this sheet to see what I mean.
> 
> I think this is the job of a i18n tool. The only things we will have to define will be the patterns to build a title correctly in the concerned language.

True.

Just a note: I don’t know if you have noted, but I joined gender titles like `abbot` and `abbess` into one title `abbot`. Hope you are okay with and that you take this into account. :smiley:
